config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  get 'pages/type'
  get 'pages/department'
  

  devise_for :users
  resources :users
  resources :departments
  resources :types 
  resources :orders
  root to: 'pages#home'
end

app/models/department.rb
class Department < ActiveRecord::Base
    has_many :order
end

app/models/io_request.rb
class IoRequest < ActiveRecord::Base
  belongs_to :department
  belongs_to :type
  belongs_to :user
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :department
  belongs_to :type
  belongs_to :user
end

app/models/type.rb
class Type < ActiveRecord::Base
    has_and_belongs_to_many :order
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  enum role: [:user, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
    
   
    
    def new
        @department = Department.new
    end
    
    def create
        @departments = Department.create(department_params)
        redirect_to root_path
    end
    
    private
    def department_params
        params.require(:department).permit(:name)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    def new
        @order = Order.new
        render :show_form
    end
    def create
        @order = Order.create(order_params)
        @order.user_id = current_user.id
        @orders  = Order.all
        render :hide_form
    end
    
    def edit 
        @order = Order.edit(params[:id])
        render :show_form
    end
    def update
      @order = Order.find(params[:id])
      @order.update_attributes(order_params)
      
    end
        
        
    def destroy
        @order = Order.find(params[:id])
        @order.destroy
        @orders = Order.all
        
    end
    private
    def order_params
        params.require(:order).permit(:department_id,:type_id,:problem,:user_id , :completed)
        
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @oders = Order.all
  end
  
  def type
    @types = Type.all
    
  end
  
  def department
    @departments = Department.all
    
  end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
    def index
        @types = Type.all
        
    end
    
    def new
    
        @type = Type.new
    end
    
    def create
        @type = Type.create(type_params)
        redirect_to root_path
        @types = Type.all
    end
    def destroy
        @type = Type.find(params[:id])
        @type.destroy
        @types = Type.all
        
    end
    def edit
        @type = Type.find(params[:id])
    end
    
    private
    def type_params
        params.require(:type).permit(:name)
        
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  after_action :verify_authorized

  def index
    @users = User.all
    authorize User
  end

  def show
    @user = User.find(params[:id])
    authorize @user
  end

  def update
    @user = User.find(params[:id])
    authorize @user
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    authorize user
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/departments/_department_form.html.haml
.modal-dialog
  .modal-content
    .modal-header
      %h1 New department
    = simple_form_for department , class: 'clearfix' do |f|
      .modal-body
       
        = f.input :name
      .modal-footer
        = f.submit 'Save' , class: 'btn btn-primary'
        

app/views/departments/_department_list.html.haml
= render 'departments/jumbotron'
.container 
  - if @departments.blank?
    %span.text-warning There are no tasks!
  - else 
    %table.table.table-hover.table-bordered
      %thead
        %tr
          %th Name
          %th Actions
          
          
      %tbody
        - @departments.each do |department|
          %tr
            %td
              %strong= department.name
            %td 
              = link_to department_path(department) , remote: true , method: :delete do
                %i.glyphicon.glyphicon-remove
              = link_to edit_department_path(department) , remote: true do
                %i.glyphicon.glyphicon-pencil

app/views/departments/_jumbotron.html.haml
.container
  .row
    .col-md-8.col-md-offset-3
      .jumbotron.text-center
       
        %h1
          Internal orders
          
        - if current_user
          .text-center
            = link_to 'New Departments' , new_department_path , class: 'btn btn-primary ' , remote: true
        
          .text-center
            %strong= current_user.email
      
          .text-center
            = link_to 'logout' , destroy_user_session_path , method: :delete
          

app/views/departments/create.js.erb
$('#type-list').html('<%= j(render partial: 'types/type_list', locals: {types: @types}) %>');
$('#type_modal').modal('hide');

app/views/departments/destroy.js.erb
$('#departments-list').html('<%= j(render partial: 'department_list', locals: departments: @departments})%>');

app/views/departments/new.js.erb
m = $('#department_modal');
m.html('<%= j(render partial: 'department_form', locals: {department: @department}) %>');
m.modal('show');

app/views/layouts/_jumbotron.html.haml
.container
  .row
    .col-md-8.col-md-offset-2
      .jumbotron.text-center
       
        %h1
          Internal orders
          
        - if current_user
          .text-center
            = link_to 'New Internal Order' , new_order_path , class: 'btn btn-primary ' , remote: true
        
          .text-center
            %strong= current_user.email
      
          .text-center
            = link_to 'logout' , destroy_user_session_path , method: :delete
          

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"
      button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.slim
/ navigation styled for Bootstrap 3.0
nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      ul.nav.navbar-nav
        == render 'layouts/navigation_links'
        

app/views/layouts/_navigation_links.html.slim
- if user_signed_in?
  
  li = link_to 'Edit account', edit_user_registration_path
  li = link_to 'Sign out', destroy_user_session_path, :method=>'delete'
- else
  li = link_to 'Sign in', new_user_session_path
  li = link_to 'Sign up', new_user_registration_path
- if user_signed_in?
  - if current_user.admin?
    li = link_to 'Types' ,  pages_type_path
    li = link_to 'Departments' , pages_department_path
    li = link_to 'Users', users_path
    

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'Internal Orders'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Internal Orders'}"
    == stylesheet_link_tag "application", :media => 'all'
    == javascript_include_tag 'application'
    == csrf_meta_tags
  body
    header
      == render 'layouts/navigation'
    main[role="main"]
      == render 'layouts/messages'
     
      == yield

app/views/orders/_order_form.html.haml
.modal-dialog
  .modal-content
    .modal-header
      %h1 New Internal Order
    = simple_form_for order , class: 'clearfix' , remote: true do |f|
      .modal-body
        = f.association :department
        = f.association :type
        = f.input :problem
        - if current_user.admin?
          = f.input :completed , as: :string , input_html: {"data-provide"=> "datepicker"}
      .modal-footer
        = f.submit 'Save' , class: 'btn btn-primary'

app/views/orders/_order_list.html.haml
= render 'layouts/jumbotron'
.container 
  - if @orders.blank?
    %span.text-warning There are no internal order
  - else 
    %table.table.table-hover.table-bordered
      %thead
        %tr
          %th Department
          %th Type
          %th Problem
          %th Created at
          %th Completed 
          %th Actions
      %tbody
        - @orders.each do |io_request|
          %tr
            %td
              %strong= io_request.department.name
            %td.text-danger= io_request.type.name
            %td= io_request.problem
            %td.text-info= io_request.created_at
            %td.text-success= io_request.completed
            %td 
              = link_to order_path(io_request) , remote: true , method: :delete do 
                %i.glyphicon.glyphicon-remove
              = link_to edit_order_path(io_request) , remote: true do 
                %i.glyphicon.glyphicon-pencil
            
            
            

app/views/orders/create.js.erb
$('#orders-list').html('<%= j(render partial: 'orders/order_list', locals: {orders: @orders}) %>');
$('#modal').modal('hide');

app/views/orders/destroy.js.erb
$('#orders-list').html('<%= j(render partial: 'order_list', locals: {orders: @orders})%>');

app/views/orders/hide_form.js.erb
$('#orders-list').html('<%= j(render partial: 'orders/order_list', locals: {orders: @orders}) %>');
$('#modal').modal('hide');

app/views/orders/new.js.erb
m = $('#modal');
m.html('<%= j(render partial: 'order_form', locals: {order: @order}) %>');
m.modal('show');
$('#modal').integrateDatepicker();

app/views/orders/show_form.js.erb
m = $('#modal');
m.html('<%= j(render partial: 'order_form', locals: {order: @order}) %>');
m.modal('show');
$('#modal').integrateDatepicker();

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/pages/department.html.haml
#departments-list.container
  = render partial: 'departments/department_list', locals: {departments: @departments}
#department_modal.modal.fade{:role => "dialog", :tabindex => "-1"}
            
            

app/views/pages/home.html.haml
#orders-list.container
  = render partial: 'orders/order_list', locals: {orders: @orders}
#modal.modal.fade{:role => "dialog", :tabindex => "-1"}

app/views/pages/type.html.haml
#type-list.container
  = render partial: 'types/type_list', locals: {types: @types}
#type_modal.modal.fade{:role => "dialog", :tabindex => "-1"}
            
            

app/views/types/_jumbotron.html.haml
.container
  .row
    .col-md-8.col-md-offset-3
      .jumbotron.text-center
       
        %h1
          Internal orders
          
        - if current_user
          .text-center
            = link_to 'New types ' , new_type_path , class: 'btn btn-primary ' , remote: true
        
          .text-center
            %strong= current_user.email
      
          .text-center
            = link_to 'logout' , destroy_user_session_path , method: :delete
          

app/views/types/_type_form.html.haml
.modal-dialog
  .modal-content
    .modal-header
      %h1 New type
    = simple_form_for type , class: 'clearfix' do |f|
      .modal-body
       
        = f.input :name
      .modal-footer
        = f.submit 'Save' , class: 'btn btn-primary'
        

app/views/types/_type_list.html.haml
= render 'types/jumbotron'
        
.container 
  - if @types.blank?
    %span.text-warning There are no types
  - else 
    %table.table.table-hover.table-bordered
      %thead
        %tr
          %th Problem type
          %th Actions 
         
      %tbody
        - @types.each do |type|
          %tr
            
            %td.text-danger= type.name
            %td 
              = link_to type_path(type) , remote: true , method: :delete do 
                %i.glyphicon.glyphicon-remove
              = link_to edit_type_path(type) , remote: true  do  
                %i.glyphicon.glyphicon-pencil

app/views/types/create.js.erb
$('#type-list').html('<%= j(render partial: 'types/type_list', locals: {types: @types}) %>');
$('#type_modal').modal('hide');

app/views/types/destroy.js.erb
$('#types-list').html('<%= j(render partial: 'type_list', locals: {types: @types})%>');

app/views/types/new.js.erb
m = $('#type_modal');
m.html('<%= j(render partial: 'type_form', locals: {type: @type}) %>');
m.modal('show');

app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user %>
</td>
<td>
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
    <%= f.submit 'Change Role', :class => 'button-xs' %>
  <% end %>
</td>
<td>
  <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user %>
</td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/index.html.erb
<h3>Welcome</h3>
<p><%= link_to 'Users:', users_path %> <%= User.count %> registered</p>